cabal-version:      3.4
name:               hs-raft
version:            0.1.0.0
synopsis:           Haskell implementation of the Raft consensus protocol
-- description:
homepage:           https://github.com/LaurentRDC/hs-raft
license:            BSD-3-Clause
license-file:       LICENSE
author:             Laurent P. René de Cotret
maintainer:         laurent.decotret@outlook.com
copyright:          Laurent P. René de Cotret
category:           Network
build-type:         Simple
extra-doc-files:    CHANGELOG.md

source-repository head
    type: git
    location: https://github.com/LaurentRDC/hs-raft

common warnings
    ghc-options: -Wall
                 -Wcompat
                 -Widentities
                 -Wincomplete-uni-patterns
                 -Wincomplete-record-updates
                 -Wredundant-constraints
                 -fhide-source-paths
                 -Wpartial-fields
                 -Wunused-packages

library
    import:           warnings
    exposed-modules:  Network.Consensus.Raft
                      Network.Consensus.Raft.Client
    other-modules:    Network.Consensus.Raft.Algorithm
                      Network.Consensus.Raft.Transformer
                      Network.Consensus.Raft.Transformer.Definition
                      Network.Consensus.Raft.Transformer.Spec
                      Network.Consensus.Raft.Timer
    -- GHC 9.6+ (base 4.18+) is required to infer types properly when
    -- using io-classes
    build-depends:    base >= 4.18 && <4.23
                    , containers
                    , io-classes ^>=1.10
                    , microlens-platform ^>=0.4
                    , random ^>=1.3
                    , text >=2.1.2 && <2.2
                    , transformers ^>=0.6
                    , vector >= 0.10 && <0.14
    hs-source-dirs:   src
    default-language: Haskell2010

test-suite hs-raft-test
    import:           warnings
    default-language: Haskell2010
    type:             exitcode-stdio-1.0
    hs-source-dirs:   tests
    main-is:          Main.hs
    other-modules:    Control.Monitor
                      Control.Monitor.Predicate
                      Control.Monitor.Reason
                      Test.Network.Consensus.Raft
                      Test.Network.Consensus.Raft.Properties
                      Test.Network.Consensus.Scenario
    ghc-options:      -threaded +RTS -N
    build-depends:    base >= 4.18 && <4.23
                    , containers
                    , hs-raft
                    , io-classes
                    , io-sim
                    , random
                    , tasty ^>=1.5
                    , tasty-quickcheck ^>=0.11
                    , text
