name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v18
        with:
          mode: check
  
  build:
    needs: formatting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc:
          - '9.6'
          - '9.8'
          - '9.10'
          - '9.12'
          - '9.14'

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Configure build
        run: |
          cabal configure --disable-optimization --semaphore -j
          # Generate a plan.json
          cabal build --dry-run

      - name: Cache Cabal store
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-${{ hashFiles('**/plan.json') }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-

      - name: Build dependencies
        run: cabal build --only-dependencies

      - name: Build library
        run: cabal build

      - name: Run tests
        run: cabal test
