name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v18
        with:
          mode: check

  linting:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-scan@v1
        with:
          fail-on: note

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
          # TODO: windows tests, especially for the 'wal' library.
          #       Unfortunately, I don't have a Windows machine handy,
          #       so I can't replicate test failures
          # - 'windows-latest'
        ghc:
          - '9.6'
          - '9.8'
          - '9.10'
          - '9.12'
          - '9.14'

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Configure build
        run: |
          cabal configure --disable-optimization --semaphore -j
          # Generate a plan.json
          cabal build all --dry-run

      - name: Cache Cabal store
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ matrix.ghc }}-test-${{ hashFiles('**/plan.json') }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ matrix.ghc }}-test

      - name: Build dependencies
        run: cabal build all --only-dependencies

      - name: Build libraries
        run: cabal build all

      - name: Run tests
        run: |
          # Github Actions hosted runners don't have that much RAM,
          # which can make some tests appear to fail due to the test executable
          # being killed.
          #
          # Therefore, the amount of exploration is capped to about 1/10 of the
          # default values in CI
          cabal test raft-consensus --test-options="--schedule-bound=10 --branching-factor=2"
          cabal test wal

  benchmark:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GHC_VERSION: '9.14'

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ env.GHC_VERSION }}

      - name: Configure build
        run: |
          cabal configure --disable-tests --semaphore -j
          # Generate a plan.json
          cabal build all --project-file=cabal.optimized.project --dry-run

      - name: Cache Cabal store
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-benchmark-${{ hashFiles('**/plan.json') }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-benchmark

      - name: Build
        run: cabal build all --project-file=cabal.optimized.project

      # Run benchmarks with j1 so that we don't get interleaved output
      - name: Run benchmarks
        run: |
          cabal bench all -j1 --project-file=cabal.optimized.project

  haddock:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GHC_VERSION: '9.14'

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ env.GHC_VERSION }}

      - name: Configure build
        run: |
          cabal configure \
            --enable-documentation \
            --disable-tests \
            --disable-benchmarks \
            --disable-optimization \
            --semaphore \
            -j
          # Generate a plan.json
          cabal build all --dry-run

      - name: Cache Cabal store
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-documentation-${{ hashFiles('**/plan.json') }}
          restore-keys: |
            ${{ runner.os }}-ghc-${{ env.GHC_VERSION }}-benchmark

      - name: Build
        run: cabal haddock all --haddock-for-hackage
        
      - name: Upload Haddock artifacts
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/upload-artifact@v4
        with:
          name: haddock-artifact
          path: dist-newstyle/*-docs.tar.gz
          retention-days: 7
